### ISSUE TITLE
[backend] Backend error

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/trusted-setup#117]
Error message show in the backend server in [unirep-trusted-setup-v3-7b9d48fb97-mpxl7](https://devops.unirep.io/dashboard/c/local/explorer/pod/default/unirep-trusted-setup-v3-7b9d48fb97-mpxl7)

```
Uploading sign_up_1.zkey
Backup error
NoSuchBucket: The specified bucket does not exist.
2023-10-04T13:30:34.197821376Z     at throwDefaultError (/src/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
2023-10-04T13:30:34.197827604Z     at /src/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
2023-10-04T13:30:34.197832123Z     at de_PutObjectCommandError (/src/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5701:12)
2023-10-04T13:30:34.197836263Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-04T13:30:34.197840225Z     at async /src/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
2023-10-04T13:30:34.197843861Z     at async /src/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
2023-10-04T13:30:34.197847710Z     at async /src/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
2023-10-04T13:30:34.197851974Z     at async /src/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
2023-10-04T13:30:34.197856200Z     at async /src/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async Backup._backup (file:///src/packages/backend/src/daemons/backup.mjs:82:9) {
  '$fault': 'client',
2023-10-04T13:30:34.197867840Z   '$metadata': {
2023-10-04T13:30:34.197871344Z     httpStatusCode: 404,
2023-10-04T13:30:34.197875079Z     requestId: undefined,
2023-10-04T13:30:34.197879172Z     extendedRequestId: undefined,
2023-10-04T13:30:34.197882829Z     cfId: undefined,
2023-10-04T13:30:34.197886799Z     attempts: 1,
2023-10-04T13:30:34.197890758Z     totalRetryDelay: 0
2023-10-04T13:30:34.197894583Z   },
  Code: 'NoSuchBucket'
2023-10-04T13:30:34.197902257Z }
```

It stucks in `Uploading Sign Up contribution` step

**Comment by kittybest** [comment]
@vivianjeng 
<img width="679" alt="image" src="https://github.com/Unirep/trusted-setup/assets/9023842/fa3509e1-e24d-4975-b73f-2d250c6a130a">

set up R2 bucket under my Cloudflare account and I think it works now.
but I don't pay for the Cloudflare, will it cause any problem in the future?
